### ISSUE TITLE
formatting @example tags when tsdoc = true is broken

### ISSUE THREAD

**Issue by Luke-zhang-04** [hosseinmd/prettier-plugin-jsdoc#119]
Input: 
```js
/**
 * @examples
 *   var one= 5
 *   var two=10
 *
 *   if(one > 2) { two += one }
 */
```

Expected: 
```js
/**
 * @example
 *   var one = 5;
 *   var two = 10;
 *
 *   if (one > 2) {
 *     two += one;
 *   }
 */
```

Output:
```js
/**
 * @example Var one= 5 var two=10
 *
 * If(one > 2) { two += one }
 */
```

Config:
```yml
jsdocSpaces: 1
jsdocDescriptionWithDot: false
jsdocDescriptionTag: false
jsdocVerticalAlignment: false
jsdocKeepUnParseAbleExampleIndent: false
jsdocSingleLineComment: false
jsdocSeparateReturnsFromParam: false
tsdoc: true
```
